/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_api_v1_assets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_v1_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Content */
        get: operations["asset_content_api_v1_assets__asset_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Asset Download Url */
        post: operations["asset_download_url_api_v1_assets__asset_id__download_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Corrections */
        post: operations["save_corrections_api_v1_jobs__job_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Diagnostics */
        get: operations["job_diagnostics_api_v1_jobs__job_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Job Download Url */
        post: operations["job_download_url_api_v1_jobs__job_id__download_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerun Job */
        post: operations["rerun_job_api_v1_jobs__job_id__rerun_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Styles */
        get: operations["list_styles_api_v1_styles_get"];
        put?: never;
        /** Create Style */
        post: operations["create_style_api_v1_styles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles/{style_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Style */
        get: operations["get_style_api_v1_styles__style_id__get"];
        put?: never;
        post?: never;
        /** Delete Style */
        delete: operations["delete_style_api_v1_styles__style_id__delete"];
        options?: never;
        head?: never;
        /** Update Style */
        patch: operations["update_style_api_v1_styles__style_id__patch"];
        trace?: never;
    };
    "/api/v1/styles/{style_id}/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Style Example */
        post: operations["add_style_example_api_v1_styles__style_id__examples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles/{style_id}/examples/{example_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Style Example */
        delete: operations["delete_style_example_api_v1_styles__style_id__examples__example_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles/{style_id}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank Style */
        post: operations["rank_style_api_v1_styles__style_id__rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles/{style_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Style */
        post: operations["reindex_style_api_v1_styles__style_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlgorithmProfile
         * @enum {string}
         */
        AlgorithmProfile: "ai_dgpst_v1" | "paper_exact" | "source_2014_compat";
        /** AlignmentCorrection */
        AlignmentCorrection: {
            /** Input Points */
            input_points: [
                number,
                number
            ][];
            /** Reference Points */
            reference_points: [
                number,
                number
            ][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "alignment";
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "INPUT" | "REFERENCE" | "STYLE_EXAMPLE" | "OUTPUT" | "DEBUG" | "EXPORT";
        /** AssetResponse */
        AssetResponse: {
            /** Analysis */
            analysis?: {
                [key: string]: unknown;
            } | null;
            /** Byte Size */
            byte_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Height */
            height: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["AssetKind"];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Mime Type */
            mime_type: string;
            /** Preview Url */
            preview_url?: string | null;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
        };
        /** BackgroundCorrection */
        BackgroundCorrection: {
            /** Color */
            color?: string | null;
            mode: components["schemas"]["BackgroundMode"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "background";
        };
        /**
         * BackgroundMode
         * @enum {string}
         */
        BackgroundMode: "KEEP" | "BLUR" | "SOLID" | "REFERENCE";
        /** Body_upload_asset_api_v1_assets_upload_post */
        Body_upload_asset_api_v1_assets_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            kind: components["schemas"]["AssetKind"];
        };
        /** CorrectionRequest */
        CorrectionRequest: {
            /** Corrections */
            corrections: (components["schemas"]["MaskCorrection"] | components["schemas"]["AlignmentCorrection"] | components["schemas"]["GainCopyCorrection"] | components["schemas"]["EyeCorrection"] | components["schemas"]["BackgroundCorrection"])[];
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /**
             * Input Asset Id
             * Format: uuid
             */
            input_asset_id: string;
            /** Reference Asset Id */
            reference_asset_id?: string | null;
            settings?: components["schemas"]["TransferSettingsRequest"];
            /** Style Id */
            style_id?: string | null;
        };
        /** CreateStyleRequest */
        CreateStyleRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
            /** Name */
            name: string;
            /** Rights Confirmed */
            rights_confirmed: boolean;
        };
        /** DiagnosticArtifactResponse */
        DiagnosticArtifactResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Download Url */
            download_url?: string | null;
            /** Kind */
            kind: string;
        };
        /** DownloadUrlResponse */
        DownloadUrlResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Url */
            url: string;
        };
        /** EyeCorrection */
        EyeCorrection: {
            /**
             * Eye
             * @enum {string}
             */
            eye: "LEFT" | "RIGHT";
            /** Highlight Rotation Degrees */
            highlight_rotation_degrees?: number | null;
            /** Highlight Scale */
            highlight_scale?: number | null;
            /** Iris Radius */
            iris_radius?: number | null;
            /** Pupil Center */
            pupil_center: [
                number,
                number
            ];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "eye";
        };
        /** GainCopyCorrection */
        GainCopyCorrection: {
            /** Levels */
            levels?: number[];
            /** Source Polygon */
            source_polygon: [
                number,
                number
            ][];
            /** Target Polygon */
            target_polygon: [
                number,
                number
            ][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "gain_copy";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDiagnosticsResponse */
        JobDiagnosticsResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["DiagnosticArtifactResponse"][];
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            };
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** JobResponse */
        JobResponse: {
            algorithm_profile: components["schemas"]["AlgorithmProfile"];
            /** Corrections */
            corrections: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Diagnostics Summary */
            diagnostics_summary: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Message Safe */
            error_message_safe: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Input Asset Id
             * Format: uuid
             */
            input_asset_id: string;
            /** Input Preview Url */
            input_preview_url?: string | null;
            /** Output Asset Id */
            output_asset_id?: string | null;
            /** Output Url */
            output_url?: string | null;
            /** Progress */
            progress: number;
            /** Reference Asset Id */
            reference_asset_id: string | null;
            /** Reference Preview Url */
            reference_preview_url?: string | null;
            /** Selected Style Example Id */
            selected_style_example_id: string | null;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            stage: components["schemas"]["ProcessingStage"];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
            /** Style Id */
            style_id: string | null;
            /** Warnings */
            warnings?: components["schemas"]["JobWarning"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCEL_REQUESTED" | "CANCELLED" | "EXPIRED";
        /** JobWarning */
        JobWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @default warning
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
        };
        /** MaskCorrection */
        MaskCorrection: {
            /**
             * Operation
             * @enum {string}
             */
            operation: "ADD" | "REMOVE";
            /** Points */
            points: [
                number,
                number
            ][];
            /** Radius */
            radius: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mask";
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * OutputFormat
         * @enum {string}
         */
        OutputFormat: "PNG" | "JPEG";
        /**
         * ProcessingStage
         * @enum {string}
         */
        ProcessingStage: "VALIDATING" | "DECODING" | "FACE_LANDMARKS" | "SEGMENTATION" | "QUALITY_ANALYSIS" | "REFERENCE_SELECTION" | "AFFINE_ALIGNMENT" | "PIECEWISE_ALIGNMENT" | "DENSE_ALIGNMENT" | "MULTISCALE_TRANSFER" | "EYE_HIGHLIGHTS" | "BACKGROUND" | "POSTPROCESSING" | "UPLOADING_OUTPUT" | "COMPLETED";
        /** RankStyleRequest */
        RankStyleRequest: {
            /**
             * Input Asset Id
             * Format: uuid
             */
            input_asset_id: string;
            /**
             * Limit
             * @default 3
             */
            limit: number;
        };
        /** RankStyleResponse */
        RankStyleResponse: {
            /**
             * Input Asset Id
             * Format: uuid
             */
            input_asset_id: string;
            /** Results */
            results: components["schemas"]["RankedStyleExample"][];
            /**
             * Style Id
             * Format: uuid
             */
            style_id: string;
        };
        /** RankedStyleExample */
        RankedStyleExample: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            };
            /**
             * Example Id
             * Format: uuid
             */
            example_id: string;
            /** Score */
            score: number;
        };
        /** StyleExampleResponse */
        StyleExampleResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Indexed */
            indexed: boolean;
            /** Quality */
            quality: {
                [key: string]: unknown;
            };
        };
        /** StyleResponse */
        StyleResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Example Count */
            example_count: number;
            /** Examples */
            examples: components["schemas"]["StyleExampleResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Public */
            is_public: boolean;
            /** Name */
            name: string;
            /** Preview Url */
            preview_url?: string | null;
            /** Rights Confirmed */
            rights_confirmed: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TransferSettingsRequest */
        TransferSettingsRequest: {
            /**
             * Algorithm Profile
             * @default ai_dgpst_v1
             * @constant
             */
            algorithm_profile: "ai_dgpst_v1";
            /** Background Color */
            background_color?: string | null;
            /** @default KEEP */
            background_mode: components["schemas"]["BackgroundMode"];
            /**
             * Inference Steps
             * @default 30
             */
            inference_steps: number;
            /**
             * Jpeg Quality
             * @default 95
             */
            jpeg_quality: number;
            /** @default PNG */
            output_format: components["schemas"]["OutputFormat"];
            /**
             * Random Seed
             * @default 0
             */
            random_seed: number;
            /**
             * Structure Strength
             * @default 0.9
             */
            structure_strength: number;
            /**
             * Style Strength
             * @default 0.75
             */
            style_strength: number;
        };
        /** UpdateStyleRequest */
        UpdateStyleRequest: {
            /** Description */
            description?: string | null;
            /** Is Public */
            is_public?: boolean | null;
            /** Name */
            name?: string | null;
            /** Rights Confirmed */
            rights_confirmed?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_asset_api_v1_assets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_v1_assets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_content_api_v1_assets__asset_id__content_get: {
        parameters: {
            query?: {
                download?: boolean;
                token?: string | null;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_download_url_api_v1_assets__asset_id__download_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_corrections_api_v1_jobs__job_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_diagnostics_api_v1_jobs__job_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDiagnosticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_download_url_api_v1_jobs__job_id__download_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_job_api_v1_jobs__job_id__rerun_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_styles_api_v1_styles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleResponse"][];
                };
            };
        };
    };
    create_style_api_v1_styles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStyleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_style_api_v1_styles__style_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_style_api_v1_styles__style_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_style_api_v1_styles__style_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStyleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_style_example_api_v1_styles__style_id__examples_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleExampleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_style_example_api_v1_styles__style_id__examples__example_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
                example_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_style_api_v1_styles__style_id__rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankStyleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankStyleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_style_api_v1_styles__style_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                style_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
