from __future__ import annotations

from enum import StrEnum


class AssetKind(StrEnum):
    INPUT = "INPUT"
    REFERENCE = "REFERENCE"
    STYLE_EXAMPLE = "STYLE_EXAMPLE"
    OUTPUT = "OUTPUT"
    DEBUG = "DEBUG"
    EXPORT = "EXPORT"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class ProcessingStage(StrEnum):
    VALIDATING = "VALIDATING"
    DECODING = "DECODING"
    FACE_LANDMARKS = "FACE_LANDMARKS"
    SEGMENTATION = "SEGMENTATION"
    QUALITY_ANALYSIS = "QUALITY_ANALYSIS"
    REFERENCE_SELECTION = "REFERENCE_SELECTION"
    AFFINE_ALIGNMENT = "AFFINE_ALIGNMENT"
    PIECEWISE_ALIGNMENT = "PIECEWISE_ALIGNMENT"
    DENSE_ALIGNMENT = "DENSE_ALIGNMENT"
    MULTISCALE_TRANSFER = "MULTISCALE_TRANSFER"
    EYE_HIGHLIGHTS = "EYE_HIGHLIGHTS"
    BACKGROUND = "BACKGROUND"
    POSTPROCESSING = "POSTPROCESSING"
    UPLOADING_OUTPUT = "UPLOADING_OUTPUT"
    COMPLETED = "COMPLETED"


class AlgorithmProfile(StrEnum):
    AI_DGPST_V1 = "ai_dgpst_v1"
    PAPER_EXACT = "paper_exact"
    SOURCE_2014_COMPAT = "source_2014_compat"


class ArtifactKind(StrEnum):
    OUTPUT = "OUTPUT"
    INPUT_MASK = "INPUT_MASK"
    REFERENCE_MASK = "REFERENCE_MASK"
    AFFINE_PREVIEW = "AFFINE_PREVIEW"
    PIECEWISE_PREVIEW = "PIECEWISE_PREVIEW"
    DENSE_PREVIEW = "DENSE_PREVIEW"
    ENERGY = "ENERGY"
    GAIN = "GAIN"
    OTHER = "OTHER"


class BackgroundMode(StrEnum):
    KEEP = "KEEP"
    BLUR = "BLUR"
    SOLID = "SOLID"
    REFERENCE = "REFERENCE"


class OutputFormat(StrEnum):
    PNG = "PNG"
    JPEG = "JPEG"


TERMINAL_JOB_STATUSES = {
    JobStatus.SUCCEEDED,
    JobStatus.FAILED,
    JobStatus.CANCELLED,
    JobStatus.EXPIRED,
}
